### ISSUE TITLE
With the upgrade to TYPO3 9.5.14 login into backend is not possible any longer

### ISSUE THREAD

**Issue by mtelgkamp** [marketing-factory/oauth2#21]
I have not found any problems in the log, yet. The TYPO3 auth log says
`User XYZ logged in from IPADDRESS	(msg#255.1.1)`
But the login screen says

> Your login attempt did not succeed
>
> Make sure to spell your username and password correctly, including upper/lowercase characters.

The problem happens with multiple different TYPO3 installations.

**Comment by haassie** [comment]
Maybe this has something to do with https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7.x/Feature-90351-ConfigureTYPO3-shippedCookiesWithSameSiteFlag.html.

**Comment by mtelgkamp** [comment]
Confirmed: setting `$GLOBALS[TYPO3_CONF_VARS][BE][cookieSameSite]='lax';` solves the login the problem

**Comment by infabo** [comment]
I assume it's the redirect from the OpenID-Provider back to the BE-login URL, right?

Is there any solution other than setting `cookieSameSite` to `lax`?

**Comment by infabo** [comment]
PS:

It still works in Chrome 87 with `cookieSameSite => strict` - but not in Firefox 84.

**Comment by infabo** [comment]
Any other solution instead of setting cookie to LAX?

**Comment by zenobio93** [comment]
After some research, it is not possible to work without `sameSite = lax`, as these are 3rd party login providers that could be hosted on other domains.

Reason is that browsers won't set an cookie with `sameSite = strict` while beeing redirected from another domain.
