### ISSUE TITLE
Replace usage of api with read_api in getAuthorizationUrl

### ISSUE THREAD

**Issue by garbast** [marketing-factory/oauth2#25]
Using api scope, while the same can be achieved with read_api, gives to many rights that are not needed.

This could be reduced in https://github.com/marketing-factory/oauth2/blob/4f051cb62b5f49bf75b976727a7b79cc94d8a5c0/Classes/ResourceServer/GitLab.php#L102

**Comment by infabo** [comment]
+1

**Comment by garbast** [comment]
Where do we go from here with this request?

**Comment by christian-fries** [comment]
Because the change of the scope is a breaking change, I propose to target a new major version

**Comment by garbast** [comment]
Sadly this issues was ignored for 2 1/1 years for now.  Seams to not be relevant for the extension author.

**Comment by infabo** [comment]
> Because the change of the scope is a breaking change, I propose to target a new major version

Requiring less permissions is not a breaking change. All existing applications would work flawlessly with full "api" permissions.

**Comment by christian-fries** [comment]
@infabo which makes it even easier to integrate this change. The ticket should be reopened.

**Comment by ischmittis** [comment]
Have a look at https://github.com/marketing-factory/oauth2/pull/53. We will work on this during our next Update in this month.
