### ISSUE TITLE
Compatibility v12

### ISSUE THREAD

**Issue by r3h6** [marketing-factory/oauth2#46]
What are your plans with this extension for supporting TYPO3 v12?
Do you merge the pull request https://github.com/marketing-factory/oauth2/pull/45?

**Comment by infabo** [comment]
I am afraid to say, but this repository/extension looks abandoned.

**Comment by tehplague** [comment]
As of version 3.1.0, oauth2 is compatible with TYPO3 12 and I just published experimental support for TYPO3 13 (which might break in the future, since TYPO3 13.0 can still have bugs).
